### PR TITLE
feat: added variable for passphrase protected ssh keys.

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description
- Added SSH key passphrase validation to be included in the Method if the Authentication type is SSH
- [Issue - 6547](https://github.ibm.com/goldeneye/issues/issues/6547) can be referred for more information.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
@imprateeksh are you still working on this? PR is still in draft mode

**Comment by imprateeksh** [comment]
> @imprateeksh are you still working on this? PR is still in draft mode

Hi @ocofaigh - I have made the changes and the PR is now ready for review.

**Review by toddgiguere — APPROVED** [review]

**Review by daniel-butler-irl — APPROVED** [review]

**Review by daniel-butler-irl — CHANGES_REQUESTED** [review]
@imprateeksh This is great thanks, could you just add a note to the authentication section here: https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper?tab=readme-ov-file#notes
With details on setting the passphrase for the ssh key if needed.

**Comment by imprateeksh** [comment]
> @imprateeksh This is great thanks, could you just add a note to the authentication section here: https://github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper?tab=readme-ov-file#notes With details on setting the passphrase for the ssh key if needed.

Hi @daniel-butler-irl - Could you please have a look at the notes once?

**Review by daniel-butler-irl — APPROVED** [review]

**Pull request merged**
