### PR TITLE
feat: simplify testprojects TearDown logic

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Simplified the TearDown logic in the testprojects package, more specifically around when TearDown is skipped for both resources and the parent stack project.

Added two new private functions in testprojects to wrap the logic around when both resource and project undeployment should take place to easier manage the logic in the future. Also added some new unit tests for these two functions to test all the various permutations and outcomes.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Simplified the logic around when resources or projects should get deleted during TestTearDown in the testprojects package, also added unit tests to verify all permutations.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]
@toddgiguere I'm approving this but won't merge if you want to continue testing. Would be nice to have it merged before the weekend though so renovate would push it out to all repos

**Comment by toddgiguere** [comment]
Have done some additional testing locally with these changes on an existing project stack, and changes appear to be working correctly.

**Pull request merged**
